"""Crossing-only SAT model for crossing-maximal simple drawings.

The model combines three ingredients:

1. a sparse GF(2) basis generated by pairs of edge-vertex switches, which
   automatically enforces every odd-K4 and even-2K3 parity condition;
2. a 5-vertex local dictionary, encoded as a reduced multi-valued decision
   diagram, which enforces simple realizability;
3. an optional induction witness: after deleting vertex 0, edge 12 is
   uncrossed, while 12 crosses 03 in the full drawing.

Only crossing pairs are represented.  No cyclic rotations or directed
crossing variables are introduced.
"""

from __future__ import annotations

import argparse
import itertools
import time
from pathlib import Path

from pysat.formula import CNF, IDPool
from pysat.solvers import Solver

from crossing_model_explore import (
    labelled_orbit,
    normalized_pair,
    pattern_from_rotation,
    read_rotation_systems,
)
from sparse_parity_basis import (
    crossing_columns,
    independent_subset,
    matching_edges,
    triangle_generators,
)


ROOT = Path(__file__).resolve().parent


def build_reduced_mdd(patterns: set[tuple[int, ...]]):
    """Build a reduced ordered MDD for five ternary variables."""
    width = len(next(iter(patterns)))
    prefix_to_node_next = {pattern: 0 for pattern in patterns}  # terminal id
    nodes_by_depth: dict[int, list[dict[int, int]]] = {}

    for depth in range(width - 1, -1, -1):
        prefixes = sorted({pattern[:depth] for pattern in patterns})
        signatures_by_prefix = {}
        for prefix in prefixes:
            transitions = {}
            for value in range(3):
                child_prefix = prefix + (value,)
                if child_prefix in prefix_to_node_next:
                    transitions[value] = prefix_to_node_next[child_prefix]
            signatures_by_prefix[prefix] = tuple(sorted(transitions.items()))

        signatures = sorted(set(signatures_by_prefix.values()))
        signature_to_node = {signature: i for i, signature in enumerate(signatures)}
        nodes_by_depth[depth] = [dict(signature) for signature in signatures]
        prefix_to_node_next = {
            prefix: signature_to_node[signature]
            for prefix, signature in signatures_by_prefix.items()
        }

    if len(nodes_by_depth[0]) != 1:
        raise ValueError("MDD must have one root")
    return nodes_by_depth


def add_xor_equivalence(cnf: CNF, vpool: IDPool, output: int, inputs: list[int], constant: int):
    """Encode output = constant XOR XOR(inputs) with a short Tseitin chain."""
    if not inputs:
        cnf.append([output if constant else -output])
        return

    target = -output if constant else output
    if len(inputs) == 1:
        source = inputs[0]
        cnf.append([-target, source])
        cnf.append([target, -source])
        return

    current = inputs[0]
    for index, source in enumerate(inputs[1:], start=1):
        result = target if index == len(inputs) - 1 else vpool.id(("xor", output, index))
        # result <-> current XOR source
        cnf.append([-current, -source, -result])
        cnf.append([current, source, -result])
        cnf.append([current, -source, result])
        cnf.append([-current, source, result])
        current = result


def add_k5_mdd(
    cnf: CNF,
    vpool: IDPool,
    five: tuple[int, ...],
    crossing_vars: dict[tuple[tuple[int, int], tuple[int, int]], int],
    mdd,
):
    quads = list(itertools.combinations(five, 4))

    def node_var(depth: int, node: int) -> int:
        return vpool.id(("mdd", five, depth, node))

    for depth in range(5):
        quad = quads[depth]
        state_vars = [crossing_vars[normalized_pair(*pair)] for pair in matching_edges(quad)]
        for node, transitions in enumerate(mdd[depth]):
            active = None if depth == 0 else node_var(depth, node)
            for state, state_var in enumerate(state_vars):
                clause = []
                if active is not None:
                    clause.append(-active)
                clause.append(-state_var)
                if state not in transitions:
                    cnf.append(clause)
                elif depth < 4:
                    clause.append(node_var(depth + 1, transitions[state]))
                    cnf.append(clause)
                # At depth 4 an existing transition reaches the accepting terminal.


def minimal_k5_nogoods(allowed5: set[tuple[int, ...]]):
    """Return the 20 ternary and 45 quaternary minimal forbidden patterns."""
    triple_forbidden = set()
    for positions in itertools.combinations(range(5), 3):
        projection = {tuple(pattern[i] for i in positions) for pattern in allowed5}
        for values in itertools.product(range(3), repeat=3):
            if values not in projection:
                triple_forbidden.add(tuple(zip(positions, values)))

    four_forbidden = set()
    for positions in itertools.combinations(range(5), 4):
        projection = {tuple(pattern[i] for i in positions) for pattern in allowed5}
        for values in itertools.product(range(3), repeat=4):
            if values in projection:
                continue
            assignment = dict(zip(positions, values))
            if any(
                tuple((position, assignment[position]) for position in triple_positions)
                in triple_forbidden
                for triple_positions in itertools.combinations(positions, 3)
            ):
                continue
            four_forbidden.add(tuple(zip(positions, values)))

    result = sorted(triple_forbidden) + sorted(four_forbidden)
    if len(result) != 65:
        raise ValueError(f"expected 65 minimal K5 nogoods, got {len(result)}")
    return result


def add_k5_nogoods(cnf, five, crossing_vars, nogoods):
    quads = list(itertools.combinations(five, 4))
    state_vars = [
        [crossing_vars[normalized_pair(*pair)] for pair in matching_edges(quad)]
        for quad in quads
    ]
    for nogood in nogoods:
        cnf.append([-state_vars[position][state] for position, state in nogood])


def build_instance(
    n: int,
    induction_witness: bool = False,
    all_deletion_witnesses: bool = False,
    native_xor: bool = False,
    k5_encoding: str = "nogoods",
    parity_encoding: str = "basis",
    return_metadata: bool = False,
):
    started = time.perf_counter()
    vpool = IDPool()
    cnf = CNF()
    xor_clauses: list[tuple[list[int], bool]] = []

    columns = crossing_columns(n)
    pairs_by_column = [None] * len(columns)
    for pair, column in columns.items():
        pairs_by_column[column] = pair
    crossing_vars = {pair: vpool.id(("cross", pair)) for pair in columns}

    expected_dimension = n * (n - 1) * (2 * n - 7) // 6
    incidence = None
    selected = []
    if parity_encoding == "basis":
        generators = triangle_generators(n, columns)
        selected = independent_subset(generators)
        if len(selected) != expected_dimension:
            raise ValueError((len(selected), expected_dimension))
        basis_vars = [vpool.id(("basis", name)) for name, _ in selected]

        incidence = [[] for _ in columns]
        for basis_var, (_, vector) in zip(basis_vars, selected, strict=True):
            remaining = vector
            while remaining:
                bit = remaining & -remaining
                incidence[bit.bit_length() - 1].append(basis_var)
                remaining ^= bit

        # The convex drawing is the affine origin: for a<b<c<d, ac crosses bd.
        for column, pair in enumerate(pairs_by_column):
            vertices = tuple(sorted(set(pair[0]) | set(pair[1])))
            base_pair = normalized_pair(*matching_edges(vertices)[1])
            base = int(pair == base_pair)
            if native_xor:
                xor_clauses.append(([crossing_vars[pair]] + incidence[column], bool(base)))
            else:
                add_xor_equivalence(
                    cnf,
                    vpool,
                    crossing_vars[pair],
                    incidence[column],
                    base,
                )

        # Parity already says each K4 has one or three crossings; exclude three.
        for quad in itertools.combinations(range(n), 4):
            choices = [crossing_vars[normalized_pair(*pair)] for pair in matching_edges(quad)]
            cnf.append([-value for value in choices])
    elif parity_encoding == "direct":
        if not native_xor:
            raise ValueError("direct parity encoding currently requires --native-xor")
        for quad in itertools.combinations(range(n), 4):
            choices = [crossing_vars[normalized_pair(*pair)] for pair in matching_edges(quad)]
            cnf.append(choices)
            for first, second in itertools.combinations(choices, 2):
                cnf.append([-first, -second])

        all_vertices = set(range(n))
        for six in itertools.combinations(range(n), 6):
            six_set = set(six)
            for first in itertools.combinations(six, 3):
                second = tuple(sorted(six_set - set(first)))
                if tuple(first) > second:
                    continue
                variables = [
                    crossing_vars[normalized_pair(e1, e2)]
                    for e1 in itertools.combinations(first, 2)
                    for e2 in itertools.combinations(second, 2)
                ]
                xor_clauses.append((variables, False))
    else:
        raise ValueError(parity_encoding)

    cm5_rotations = read_rotation_systems(ROOT / "cm5_unlabeled.json0")
    cm5_patterns = [pattern_from_rotation(rs) for rs in cm5_rotations]
    allowed5 = labelled_orbit(5, cm5_patterns)
    if k5_encoding == "mdd":
        mdd = build_reduced_mdd(allowed5)
        for five in itertools.combinations(range(n), 5):
            add_k5_mdd(cnf, vpool, five, crossing_vars, mdd)
    elif k5_encoding == "nogoods":
        nogoods = minimal_k5_nogoods(allowed5)
        for five in itertools.combinations(range(n), 5):
            add_k5_nogoods(cnf, five, crossing_vars, nogoods)
    else:
        raise ValueError(k5_encoding)

    # Every edge is crossed by at least one independent edge.
    vertices = set(range(n))
    for edge in itertools.combinations(range(n), 2):
        rest = sorted(vertices - set(edge))
        cnf.append(
            [
                crossing_vars[normalized_pair(edge, other)]
                for other in itertools.combinations(rest, 2)
            ]
        )

    if induction_witness:
        if n < 4:
            raise ValueError("induction witness needs vertices 0,1,2,3")
        witness_edge = (1, 2)
        # Edge 12 is uncrossed after deleting 0.
        for other in itertools.combinations(range(3, n), 2):
            cnf.append([-crossing_vars[normalized_pair(witness_edge, other)]])
        # The relation i<j iff 1i crosses 2j is a tournament here.  The
        # acyclicity theorem for edge-crossing relations makes it a total
        # order, so labels 3,...,n-1 may be fixed in that order.
        for i, j in itertools.combinations(range(3, n), 2):
            cnf.append([crossing_vars[normalized_pair((1, i), (2, j))]])
        # It is crossed in the full drawing; call one crossing partner 03.
        cnf.append([crossing_vars[normalized_pair(witness_edge, (0, 3))]])
        # Order the remaining vertices by whether 0k crosses 12.
        star = [crossing_vars[normalized_pair(witness_edge, (0, k))] for k in range(3, n)]
        for earlier, later in zip(star, star[1:]):
            cnf.append([earlier, -later])

    if all_deletion_witnesses:
        all_vertices = set(range(n))
        for deleted in range(n):
            remaining = sorted(all_vertices - {deleted})
            witnesses = []
            for edge in itertools.combinations(remaining, 2):
                witness = vpool.id(("deletion-witness", deleted, edge))
                witnesses.append(witness)
                rest = sorted(all_vertices - {deleted} - set(edge))
                for other in itertools.combinations(rest, 2):
                    cnf.append([-witness, -crossing_vars[normalized_pair(edge, other)]])
            cnf.append(witnesses)

    stats = {
        "n": n,
        "variables": vpool.top,
        "clauses": len(cnf.clauses),
        "basis_dimension": len(selected) if parity_encoding == "basis" else None,
        "max_crossing_basis_width": max(map(len, incidence)) if incidence else None,
        "build_seconds": time.perf_counter() - started,
        "xor_clauses": len(xor_clauses),
    }
    if return_metadata:
        return cnf, xor_clauses, stats, {
            "crossing_vars": crossing_vars,
            "pairs_by_column": pairs_by_column,
        }
    return cnf, xor_clauses, stats


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("n", type=int)
    parser.add_argument("--induction-witness", action="store_true")
    parser.add_argument("--all-deletion-witnesses", action="store_true")
    parser.add_argument("--solver", default="cadical195")
    parser.add_argument("--native-xor", action="store_true")
    parser.add_argument("--k5-encoding", choices=("nogoods", "mdd"), default="nogoods")
    parser.add_argument("--parity-encoding", choices=("basis", "direct"), default="basis")
    parser.add_argument("--time-limit", type=float)
    parser.add_argument("--cnf", type=Path)
    args = parser.parse_args()

    cnf, xor_clauses, stats = build_instance(
        args.n,
        args.induction_witness,
        args.all_deletion_witnesses,
        args.native_xor,
        args.k5_encoding,
        args.parity_encoding,
    )
    print("build", stats, flush=True)
    if args.cnf:
        cnf.to_file(args.cnf)
        print(f"wrote {args.cnf}", flush=True)

    started = time.perf_counter()
    if args.native_xor:
        import pycryptosat

        solver_kwargs = {"threads": 1}
        if args.time_limit is not None:
            solver_kwargs["time_limit"] = args.time_limit
        solver = pycryptosat.Solver(**solver_kwargs)
        solver.add_clauses(cnf.clauses)
        for variables, rhs in xor_clauses:
            solver.add_xor_clause(variables, rhs)
        satisfiable, _ = solver.solve()
        solve_seconds = time.perf_counter() - started
        result = "UNKNOWN" if satisfiable is None else ("SAT" if satisfiable else "UNSAT")
        print(
            {
                "result": result,
                "solve_seconds": solve_seconds,
                "solver": "cryptominisat-5.14.7-native-xor",
            },
            flush=True,
        )
    else:
        with Solver(name=args.solver, bootstrap_with=cnf.clauses) as solver:
            satisfiable = solver.solve()
            solve_seconds = time.perf_counter() - started
            print(
                {
                    "result": "SAT" if satisfiable else "UNSAT",
                    "solve_seconds": solve_seconds,
                    "solver_stats": solver.accum_stats(),
                },
                flush=True,
            )


if __name__ == "__main__":
    main()
