"""Independently rebuild the two-line K5 solver catalogue.

The input classification is produced by the standard-library exhaustive
enumerator in proofs/k5-completeness.  No archived catalogue or third-party
program is read.  By default this script verifies the committed solver file;
pass --write to replace it with the independently generated bytes.
"""

from __future__ import annotations

import argparse
from hashlib import sha256
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
CLASSIFICATION = ROOT / "proofs" / "k5-completeness" / "classification.json"
TARGET = ROOT / "solver" / "cm5_unlabeled.json0"
SEED_PATTERNS = ((1, 1, 1, 1, 1), (1, 1, 1, 2, 2))
EXPECTED_SHA256 = "a8f8601be31bc948bfef94e72aa5a45ceee6b722f12ef33c50534eb80fb6619c"


def generated_bytes() -> bytes:
    report = json.loads(CLASSIFICATION.read_text(encoding="utf-8"))
    rotations = []
    for pattern in SEED_PATTERNS:
        matches = [
            item["rotation"]
            for item in report["classification"]
            if tuple(item["pattern"]) == pattern and item["plane_orders"] > 0
        ]
        assert len(matches) == 1, (pattern, len(matches))
        rotations.append(matches[0])
    # The historical solver input was recorded with Windows CRLF line endings;
    # preserve them so the independently rebuilt bytes retain the recorded hash.
    output = "".join(json.dumps(rotation) + "\r\n" for rotation in rotations).encode("utf-8")
    assert sha256(output).hexdigest() == EXPECTED_SHA256
    return output


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="write the rebuilt catalogue")
    args = parser.parse_args()
    output = generated_bytes()
    if args.write:
        TARGET.write_bytes(output)
    else:
        assert TARGET.read_bytes() == output, "committed catalogue differs from independent rebuild"
    print(f"K5 solver catalogue: PASS ({len(output)} bytes, sha256={EXPECTED_SHA256})")


if __name__ == "__main__":
    main()
